### ISSUE TITLE
vnc的连接失败, 如下图

### ISSUE THREAD

**Issue by flowke** [alo7/rebirth#10]
<img width="1599" alt="运行 docker ps -a 看到的端口" src="https://user-images.githubusercontent.com/15080893/91663926-5bce1480-eb1e-11ea-9db1-e92b14232ea9.png">

<img width="859" alt="提示连接失败" src="https://user-images.githubusercontent.com/15080893/91663912-40630980-eb1e-11ea-8a87-34375e505bcb.png">

**Comment by BlackHole1** [comment]
执行下:
`docker logs reb`，贴一下日志

以及看下`32772`端口的chrome远程调试是否能连接上。

最后如果方便的话，提供下相关的`docker run`命令。

**Comment by flowke** [comment]
> 提供下相关的`docker run`命令
`docker run 命令: `  docker run -dit -P --name reb -v `pwd`/rebirth_alo7/logs:/etc/www/logs -v `pwd`/rebirth_alo7/video:/root/Downloads -e MATERIAL_URL="https://www.alo7.com/en/" -e START_VNC="yes" reb

<img width="1327" alt="截屏2020-08-31 上午10 48 15" src="https://user-images.githubusercontent.com/15080893/91678198-7bddf200-eb77-11ea-8402-eab1fa4133e1.png">

早上重新启动了下 container: `docker container start 395e32d94c46`

**再`docker ps -a`:**
<img width="1613" alt="截屏2020-08-31 上午10 50 03" src="https://user-images.githubusercontent.com/15080893/91678284-c3647e00-eb77-11ea-8708-dbad9b1c1811.png">

连接: `vnc://127.0.0.1:32775` 失败
浏览器打开:  `http://127.0.0.1:32774` ,  无法打开

**以下是 `docker logs reb` 的信息**

root@vagrant-ubuntu-trusty-64:/home/vagrant# docker logs reb
{"source":"Server","message":"Server running at http://127.0.0.1:80/","level":"info","hostname":"395e32d94c46","material_url":"https://www.alo7.com/en/","timestamp":"2020-08-31 00:04:46"}
{"source":"Server","message":"chrome open","level":"info","hostname":"395e32d94c46","material_url":"https://www.alo7.com/en/","timestamp":"2020-08-31 00:04:47"}
{"source":"Controller","message":"get record task","level":"info","hostname":"395e32d94c46","material_url":"https://www.alo7.com/en/","timestamp":"2020-08-31 00:04:50"}
{"source":"Browser","hostname":"395e32d94c46","material_url":"https://www.alo7.com/en/","level":"info","message":"set action to waiting","timestamp":"2020-08-31 00:04:50"}
{"source":"Browser","hostname":"395e32d94c46","material_url":"https://www.alo7.com/en/","recordInfo":{"material_url":"https://www.alo7.com/en/"},"level":"info","message":"open url","timestamp":"2020-08-31 00:04:50"}
31/08/2020 00:04:51 passing arg to libvncserver: -passwd
31/08/2020 00:04:51 x11vnc version: 0.9.13 lastmod: 2011-08-10  pid: 288
31/08/2020 00:04:51 Using X display :76
31/08/2020 00:04:51 rootwin: 0x298 reswin: 0x800001 dpy: 0x1b525990
31/08/2020 00:04:51
31/08/2020 00:04:51 ------------------ USEFUL INFORMATION ------------------
31/08/2020 00:04:51 X DAMAGE available on display, using it for polling hints.
31/08/2020 00:04:51   To disable this behavior use: '-noxdamage'
31/08/2020 00:04:51
31/08/2020 00:04:51   Most compositing window managers like 'compiz' or 'beryl'
31/08/2020 00:04:51   cause X DAMAGE to fail, and so you may not see any screen
31/08/2020 00:04:51   updates via VNC.  Either disable 'compiz' (recommended) or
31/08/2020 00:04:51   supply the x11vnc '-noxdamage' command line option.
31/08/2020 00:04:51
31/08/2020 00:04:51 Wireframing: -wireframe mode is in effect for window moves.
31/08/2020 00:04:51   If this yields undesired behavior (poor response, painting
31/08/2020 00:04:51   errors, etc) it may be disabled:
31/08/2020 00:04:51    - use '-nowf' to disable wireframing completely.
31/08/2020 00:04:51    - use '-nowcr' to disable the Copy Rectangle after the
31/08/2020 00:04:51      moved window is released in the new position.
31/08/2020 00:04:51   Also see the -help entry for tuning parameters.
31/08/2020 00:04:51   You can press 3 Alt_L's (Left "Alt" key) in a row to
31/08/2020 00:04:51   repaint the screen, also see the -fixscreen option for
31/08/2020 00:04:51   periodic repaints.
31/08/2020 00:04:51
31/08/2020 00:04:51 XFIXES available on display, resetting cursor mode
31/08/2020 00:04:51   to: '-cursor most'.
31/08/2020 00:04:51   to disable this behavior use: '-cursor arrow'
31/08/2020 00:04:51   or '-noxfixes'.
31/08/2020 00:04:51 using XFIXES for cursor drawing.
31/08/2020 00:04:51 GrabServer control via XTEST.
31/08/2020 00:04:51
31/08/2020 00:04:51 Scroll Detection: -scrollcopyrect mode is in effect to
31/08/2020 00:04:51   use RECORD extension to try to detect scrolling windows
31/08/2020 00:04:51   (induced by either user keystroke or mouse input).
31/08/2020 00:04:51   If this yields undesired behavior (poor response, painting
31/08/2020 00:04:51   errors, etc) it may be disabled via: '-noscr'
31/08/2020 00:04:51   Also see the -help entry for tuning parameters.
31/08/2020 00:04:51   You can press 3 Alt_L's (Left "Alt" key) in a row to
31/08/2020 00:04:51   repaint the screen, also see the -fixscreen option for
31/08/2020 00:04:51   periodic repaints.
31/08/2020 00:04:51
31/08/2020 00:04:51 XKEYBOARD: number of keysyms per keycode 7 is greater
31/08/2020 00:04:51   than 4 and 51 keysyms are mapped above 4.
31/08/2020 00:04:51   Automatically switching to -xkb mode.
31/08/2020 00:04:51   If this makes the key mapping worse you can
31/08/2020 00:04:51   disable it with the "-noxkb" option.
31/08/2020 00:04:51   Also, remember "-remap DEAD" for accenting characters.
31/08/2020 00:04:51
31/08/2020 00:04:51 X FBPM extension not supported.
31/08/2020 00:04:51 X display is not capable of DPMS.
31/08/2020 00:04:51 --------------------------------------------------------
31/08/2020 00:04:51
31/08/2020 00:04:51 Default visual ID: 0x21
31/08/2020 00:04:51 Read initial data from X display into framebuffer.
31/08/2020 00:04:51 initialize_screen: fb_depth/fb_bpp/fb_Bpl 24/32/8192
31/08/2020 00:04:51
31/08/2020 00:04:51 X display :76 is 32bpp depth=24 true color
31/08/2020 00:04:51
31/08/2020 00:04:51 Listening for VNC connections on TCP port 5920
31/08/2020 00:04:51 Listening for VNC connections on TCP6 port 5900
31/08/2020 00:04:51 Listening also on IPv6 port 5920 (socket 12)
31/08/2020 00:04:51
31/08/2020 00:04:51 Xinerama is present and active (e.g. multi-head).
31/08/2020 00:04:51 Xinerama: number of sub-screens: 1
31/08/2020 00:04:51 Xinerama: no blackouts needed (only one sub-screen)
31/08/2020 00:04:51
31/08/2020 00:04:51 fb read rate: 2169 MB/sec
31/08/2020 00:04:51 fast read: reset -wait  ms to: 10
31/08/2020 00:04:51 fast read: reset -defer ms to: 10
31/08/2020 00:04:51 The X server says there are 10 mouse buttons.
31/08/2020 00:04:51 screen setup finished.
31/08/2020 00:04:51

The VNC desktop is:      395e32d94c46:20
PORT=5920

******************************************************************************
Have you tried the x11vnc '-ncache' VNC client-side pixel caching feature yet?

The scheme stores pixel data offscreen on the VNC viewer side for faster
retrieval.  It should work with any VNC viewer.  Try it by running:

    x11vnc -ncache 10 ...

One can also add -ncache_cr for smooth 'copyrect' window motion.
More info: http://www.karlrunge.com/x11vnc/faq.html#faq-client-caching

{"source":"Browser","hostname":"395e32d94c46","material_url":"https://www.alo7.com/en/","level":"info","message":"initTimeout","timestamp":"2020-08-31 00:09:50"}
{"source":"Controller","message":"record failed","level":"info","hostname":"395e32d94c46","material_url":"https://www.alo7.com/en/","timestamp":"2020-08-31 00:09:50"}
{"source":"Server","hostname":"395e32d94c46","material_url":"https://www.alo7.com/en/","killMessage":"custom code execution complete","level":"warn","message":"the process was kill","timestamp":"2020-08-31 00:09:50"}
caught XIO error:
31/08/2020 00:09:50 deleted 64 tile_row polling images.
{"source":"Server","message":"Server running at http://127.0.0.1:80/","level":"info","hostname":"395e32d94c46","material_url":"https://www.alo7.com/en/","timestamp":"2020-08-31 10:35:01"}
{"source":"Server","message":"chrome open","level":"info","hostname":"395e32d94c46","material_url":"https://www.alo7.com/en/","timestamp":"2020-08-31 10:35:02"}
{"source":"Controller","message":"get record task","level":"info","hostname":"395e32d94c46","material_url":"https://www.alo7.com/en/","timestamp":"2020-08-31 10:35:05"}
{"source":"Browser","hostname":"395e32d94c46","material_url":"https://www.alo7.com/en/","level":"info","message":"set action to waiting","timestamp":"2020-08-31 10:35:05"}
{"source":"Browser","hostname":"395e32d94c46","material_url":"https://www.alo7.com/en/","recordInfo":{"material_url":"https://www.alo7.com/en/"},"level":"info","message":"open url","timestamp":"2020-08-31 10:35:05"}
31/08/2020 10:35:06 passing arg to libvncserver: -passwd
31/08/2020 10:35:06 x11vnc version: 0.9.13 lastmod: 2011-08-10  pid: 103
31/08/2020 10:35:06 Using X display :76
31/08/2020 10:35:06 rootwin: 0x298 reswin: 0x800001 dpy: 0xdae6c990
31/08/2020 10:35:06
31/08/2020 10:35:06 ------------------ USEFUL INFORMATION ------------------
31/08/2020 10:35:06 X DAMAGE available on display, using it for polling hints.
31/08/2020 10:35:06   To disable this behavior use: '-noxdamage'
31/08/2020 10:35:06
31/08/2020 10:35:06   Most compositing window managers like 'compiz' or 'beryl'
31/08/2020 10:35:06   cause X DAMAGE to fail, and so you may not see any screen
31/08/2020 10:35:06   updates via VNC.  Either disable 'compiz' (recommended) or
31/08/2020 10:35:06   supply the x11vnc '-noxdamage' command line option.
31/08/2020 10:35:06
31/08/2020 10:35:06 Wireframing: -wireframe mode is in effect for window moves.
31/08/2020 10:35:06   If this yields undesired behavior (poor response, painting
31/08/2020 10:35:06   errors, etc) it may be disabled:
31/08/2020 10:35:06    - use '-nowf' to disable wireframing completely.
31/08/2020 10:35:06    - use '-nowcr' to disable the Copy Rectangle after the
31/08/2020 10:35:06      moved window is released in the new position.
31/08/2020 10:35:06   Also see the -help entry for tuning parameters.
31/08/2020 10:35:06   You can press 3 Alt_L's (Left "Alt" key) in a row to
31/08/2020 10:35:06   repaint the screen, also see the -fixscreen option for
31/08/2020 10:35:06   periodic repaints.
31/08/2020 10:35:06
31/08/2020 10:35:06 XFIXES available on display, resetting cursor mode
31/08/2020 10:35:06   to: '-cursor most'.
31/08/2020 10:35:06   to disable this behavior use: '-cursor arrow'
31/08/2020 10:35:06   or '-noxfixes'.
31/08/2020 10:35:06 using XFIXES for cursor drawing.
31/08/2020 10:35:06 GrabServer control via XTEST.
31/08/2020 10:35:06
31/08/2020 10:35:06 Scroll Detection: -scrollcopyrect mode is in effect to
31/08/2020 10:35:06   use RECORD extension to try to detect scrolling windows
31/08/2020 10:35:06   (induced by either user keystroke or mouse input).
31/08/2020 10:35:06   If this yields undesired behavior (poor response, painting
31/08/2020 10:35:06   errors, etc) it may be disabled via: '-noscr'
31/08/2020 10:35:06   Also see the -help entry for tuning parameters.
31/08/2020 10:35:06   You can press 3 Alt_L's (Left "Alt" key) in a row to
31/08/2020 10:35:06   repaint the screen, also see the -fixscreen option for
31/08/2020 10:35:06   periodic repaints.
31/08/2020 10:35:06
31/08/2020 10:35:06 XKEYBOARD: number of keysyms per keycode 7 is greater
31/08/2020 10:35:06   than 4 and 51 keysyms are mapped above 4.
31/08/2020 10:35:06   Automatically switching to -xkb mode.
31/08/2020 10:35:06   If this makes the key mapping worse you can
31/08/2020 10:35:06   disable it with the "-noxkb" option.
31/08/2020 10:35:06   Also, remember "-remap DEAD" for accenting characters.
31/08/2020 10:35:06
31/08/2020 10:35:06 X FBPM extension not supported.
31/08/2020 10:35:06 X display is not capable of DPMS.
31/08/2020 10:35:06 --------------------------------------------------------
31/08/2020 10:35:06
31/08/2020 10:35:06 Default visual ID: 0x21
31/08/2020 10:35:06 Read initial data from X display into framebuffer.
31/08/2020 10:35:06 initialize_screen: fb_depth/fb_bpp/fb_Bpl 24/32/8192
31/08/2020 10:35:06
31/08/2020 10:35:06 X display :76 is 32bpp depth=24 true color
31/08/2020 10:35:06
31/08/2020 10:35:06 Listening for VNC connections on TCP port 5920
31/08/2020 10:35:06 Listening for VNC connections on TCP6 port 5900
31/08/2020 10:35:06 Listening also on IPv6 port 5920 (socket 12)
31/08/2020 10:35:06
31/08/2020 10:35:06 Xinerama is present and active (e.g. multi-head).
31/08/2020 10:35:06 Xinerama: number of sub-screens: 1
31/08/2020 10:35:06 Xinerama: no blackouts needed (only one sub-screen)
31/08/2020 10:35:06
31/08/2020 10:35:06 fb read rate: 2347 MB/sec
31/08/2020 10:35:06 fast read: reset -wait  ms to: 10
31/08/2020 10:35:06 fast read: reset -defer ms to: 10
31/08/2020 10:35:06 The X server says there are 10 mouse buttons.
31/08/2020 10:35:06 screen setup finished.
31/08/2020 10:35:06

The VNC desktop is:      395e32d94c46:20
PORT=5920

******************************************************************************
Have you tried the x11vnc '-ncache' VNC client-side pixel caching feature yet?

The scheme stores pixel data offscreen on the VNC viewer side for faster
retrieval.  It should work with any VNC viewer.  Try it by running:

    x11vnc -ncache 10 ...

One can also add -ncache_cr for smooth 'copyrect' window motion.
More info: http://www.karlrunge.com/x11vnc/faq.html#faq-client-caching

**Comment by BlackHole1** [comment]
应该是网页本身，在预期内的时间内没有调用 `rebirth.init()`导致的。尝试使用: https://www.bugs.cc/self_page/github/rebirth/webm2mp4/ 地址看下
具体可见: https://github.com/alo7/rebirth/tree/master/examples/webm2mp4

**Comment by flowke** [comment]
辛苦了, 是我网络配置的问题. 没有访问到虚拟机导致的. 
想问问声音录制上是怎么解决的

**Comment by BlackHole1** [comment]
通过设置 `chrome.tabCapture.capture` 的参数，来开启声音录制，具体可见:
https://github.com/alo7/rebirth/blob/master/src/chrome-extension/lib/recording.ts#L24
https://github.com/alo7/rebirth/blob/master/src/chrome-extension/lib/config.ts#L4

**Comment by flowke** [comment]
好家伙, 感谢. 可以随时关闭这个issue了. 我还想复杂了.

**Comment by BlackHole1** [comment]
好的
