### ISSUE TITLE
如何远程执行录制命令

### ISSUE THREAD

**Issue by runc** [alo7/rebirth#11]
如何能够远程在console控制台执行各种命令

**Comment by runc** [comment]
否则还是无法真正的自动化，毕竟执行命令部分需要手工执行。

**Comment by BlackHole1** [comment]
你指的的console控制台是指在要录制的网站中执行一些`javascript`命令么？

**Comment by runc** [comment]
> 你指的的console控制台是指在要录制的网站中执行一些`javascript`命令么？

比如我要远程，比如通过api来执行以下命令
rebirth.init();
rebirth.start();
rebirth.pause();
rebirth.resume();

这样我就可以自动录制某个网页，而现在是人肉在console上执行这些命令，无法自动化。

**Comment by runc** [comment]
> 你指的的console控制台是指在要录制的网站中执行一些`javascript`命令么？

给你gmail邮件了，方便的话，加个好友进一步交流下。

**Comment by BlackHole1** [comment]
一般来说，这个项目是录制”可控“的网站，因为要录制的网站可控，所以可以通过在网站里添加:

```
rebirth.init();
rebirth.start();
rebirth.pause();
rebirth.resume();
```
来调用录制的api

如果想要录制非可控的网站，需要在: https://github.com/alo7/rebirth/blob/master/src/chrome-extension/injected.ts
此文件下面添加你的代码，并重新构建。因为 `injected` 文件中的代码将会被注入到打开的网站里。

**Comment by subdance** [comment]
> 需要在: https://github.com/alo7/rebirth/blob/master/src/chrome-extension/injected.ts
此文件下面添加你的代码，并重新构建。

请问一下，这里的chrome-extension 构建出dist应该如何操作？

**Comment by BlackHole1** [comment]
@subdance 
只需要构建完成，直接使用就可，因为 node 中再打开chrome 的时候，代码为:
```javascript
`--load-extension=${EXTENSIONS_DIR}`,
`--disable-extensions-except=${EXTENSIONS_DIR}`,
```
代码详情见: https://github.com/alo7/rebirth/blob/master/src/lib/startChrome.js#L16-L17

而 `EXTENSIONS_DIR` 为:
```javascript
const EXTENSIONS_DIR = isDocker() ? path.join(PROJECT_DIR, 'extensions_dist') : path.join(PROJECT_DIR, 'src', 'extensions_dist');
```
代码详情见: https://github.com/alo7/rebirth/blob/master/src/lib/constants.js#L10

所以在启动 chrome 的时候，其实是直接使用 `dist` 目录下的代码

**Comment by subdance** [comment]
> 所以在启动 chrome 的时候，其实是直接使用 dist 目录下的代码
是的，extension的源码ts在chrome_extension里，浏览器指定的插件目录是dist,即源码编译后的js文件。我想了解的就是，假如我更改chrome_extension下的ts文件，再执行rebirth的启动命令，dist下的js文件会依据chrome_extension更新后的源代码重新编译吗？似乎是不生效的，更改chrome_extension下的文件并不会导致dist更新。
我想知道怎么使dist更新。
