### ISSUE TITLE
关于录制的视频质量

### ISSUE THREAD

**Issue by nogodfox** [alo7/rebirth#14]
可以成功录制，不过视频质量很低。请问有什么方法可以提高么？尝试过修改mediarecorder的视频码率和mimetype，可是没啥作用。

**Comment by BlackHole1** [comment]
这个目前暂时无法处理，之前经过排查，发现可能是和 `xvfb` 有关，打算对 `xvfb` 进行更换，更换为: `TigerVNC`，但是由于目前时间原因，没有时间进行处理。

如果感兴趣的话，欢迎提交相关PR，我很乐意去 review，并修复它。

**Comment by nogodfox** [comment]
好的，非常感谢。
