### ISSUE TITLE
基于webrtc的录制权限问题

### ISSUE THREAD

**Issue by lijian213** [alo7/rebirth#16]
getUserMedia 权限问题，这个可以处理吗？

**Comment by BlackHole1** [comment]
具体是什么问题，我记得在 chrome 启动的时候，就已经把所有的权限开到最大了

**Comment by lijian213** [comment]
Failed to GetUserMedia NotFoundError 8 Requested device not found DOMException: Requested device not found
Media access NotFoundError: Requested device not found.

浏览器报这个错误

**Comment by lijian213** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia

**Comment by BlackHole1** [comment]
这个有点奇怪，目前代码里并没有使用到 `getUserMedia` 这个方法，可以提供复现的环境(docker images / dockerfile)么

**Comment by lijian213** [comment]
应该是我们这边webrtc发起授权本地摄像头和麦克风导致的

**Comment by BlackHole1** [comment]
那报错是正常的，因为 rebirth 是运行在docker里的，肯定是没有 摄像头和麦克风的，去申请的时候，就会报错。
