### ISSUE TITLE
"initTimeout" 问题咨询

### ISSUE THREAD

**Issue by zhonghb** [alo7/rebirth#17]
当我调用 init 方法后，docker 日志提示 "initTimeout" ，如何排查这个问题呢，一下是具体的日志
![image](https://user-images.githubusercontent.com/31272843/105012913-a8889c80-5a79-11eb-9521-d7c43b54a1d1.png)

**Comment by BlackHole1** [comment]
从日志中看到，并没有调用 init 方法。

请确保你的 Init 方法已经调用，推荐是在网站加载好后，进行调用
