### ISSUE TITLE
rebirth.init() 调用不生效问题

### ISSUE THREAD

**Issue by zhonghb** [alo7/rebirth#18]
场景： 
项目部署在香港那边安全性比较严格的测试环境，在内网测试是没有问题的，上了测试之后一直报 initTimeout 的问题，由于外网访问服务器必须经过路由的服务器做跳转，所以 devtool 也无法使用

问题：
我想问一下 rebirth 项目的启动是否需要允许外网可以访问才能正常启动吗

**Comment by BlackHole1** [comment]
rebirth不需要访问外网的权限，rebirth 会启动一个server和一个chrome，其中chrome的插件会和server进行通信。

根据你的问题描述，感觉是你们在的测试环境中无法打开你们的录制地址导致的，推荐先开一个口子，进行端口反射，把 VNC 或者 devtools 端口反射出去，看看是不是无法访问导致的

**Comment by zhonghb** [comment]
好的，谢谢
