### ISSUE TITLE
白板服务器status code返回500

### ISSUE THREAD

**Issue by antyoxydant** [alo7/rebirth#21]
唯独有两个白板回放，服务器返回500
请求地址 https://storage.netless.link/pv/slices/哈希值/snapshots?timestamp=1606388365362
response：
```
{
    "title": "invalid json response body at http://akko-persistence.app.svc.cluster.local:8080/v2/slices/哈希值/snapshots?timestamp=1606388365362 reason: Unexpected end of JSON input",
    "messages": [],
    "requestId": "",
    "region": "",
    "traceStack": []
}
```
请问这种情况的原因是什么？

**Comment by BlackHole1** [comment]
这个是 netless 白板问题，非 rebirth 录制导致的。

介于 netless 白板已经被 agora 收购，推荐你按照右边的文档去提交相关的工单: https://docs.agora.io/cn/Agora%20Platform/ticket

**Comment by antyoxydant** [comment]
使用netless的账号去登录agora，但是提示账号不存在或密码错误。请问账号转移需要什么额外的操作吗？ @BlackHole1

**Comment by BlackHole1** [comment]
可以打开: https://console.netless.link/zh-CN/login/

右下角有提示
