### ISSUE TITLE
录制时出现caught XIO error

### ISSUE THREAD

**Issue by foooof** [alo7/rebirth#25]
录制某个特定web时出现这个错误,请问下是什么原因呢
`caught XIO error:`
`19/05/2021 17:22:30 deleted 64 tile_row polling images.`

**Comment by BlackHole1** [comment]
感觉像是机器本身的问题所导致的，问题的原因出在 `x11vnc` 上。

请尝试在 https://github.com/alo7/rebirth/blob/master/entrypoint.sh#L14 里，为 `x11vnc` 添加一个 `-noxrecord` 参数。

或者你尝试不要开启 VNC 连接，即： `export START_VNC=no`
