### ISSUE TITLE
无法控制录制文件的编码

### ISSUE THREAD

**Issue by sky0014** [alo7/rebirth#27]
录制出来的文件，大部分是vp8编码，少量h264编码，即使在`MediaRecorder`初始化时设置了`mimeType: "video/webm;codecs=h264"`，录出来的也大概率时vp8编码，不知道是什么原因，作者有遇到这种情况么？

**Comment by BlackHole1** [comment]
抱歉，这么晚才回复。🙇‍♂️

这是因为目前 `webm` 格式暂时不支持 `h264`，见: https://developer.mozilla.org/en-US/docs/Web/Media/Formats/codecs_parameter#webm

<img width="1047" alt="图片" src="https://user-images.githubusercontent.com/8198408/156120430-2df8b476-dbf3-4630-8a64-c02956fd86d1.png">

**Comment by BlackHole1** [comment]
你可以编写 `completeRecordAfter`，在里面调用 `FFmpeg` 来对 `webm` 格式进行转码。将其转为 mp4格式&H264 编码

**Comment by sky0014** [comment]
感谢回复，我们的业务已经上线了，反馈一下：实测chrome可以编码出h264的webm，线下测试时偶尔会失效变成vp8，线上还是挺稳定h264的。

**Comment by BlackHole1** [comment]
好的，谢谢你的反馈🚀
