### ISSUE TITLE
请问extension_dist的作用是？

### ISSUE THREAD

**Issue by 298068845** [alo7/rebirth#5]
你好，研究这个项目代码好久了，实现自动化录制的思路是在页面加载的时候document start启用content_script,然后调用injected与background通讯，再通过background调用recordding录制页面。
我理解的应该没问题吧？
但是项目里startChrome里面配置的扩展程序路径是extension_dist而不是chrome extension，这里不太理解，而且看extension_dist里的代码都是混淆过的

**Comment by BlackHole1** [comment]
`extension_dist`项目是被编译后的，其源代码是 `chrome-extension`。相关的编译 `script` 在: https://github.com/alo7/rebirth/blob/master/src/package.json#L11

相关 `webpack` 配置是: https://github.com/alo7/rebirth/blob/master/src/webpack.config.js#L35-L38

`extension_dist` 目录里只有 `background.js`、 `content_script.js`、`injected.js` 是编译的结果，其他的`background.html`、`key.pem`、`manifest.json` 则不是。

项目相关文章: https://www.bugs.cc/p/rebirth-principle-analysis/

v2ex相关的解释: https://www.v2ex.com/t/625882#r_8288127

**Comment by BlackHole1** [comment]
最近我更新下 `README.md` 方便理解
